# -*- coding: utf-8 -*-
"""aula_estatistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_IydUoFNPK03EwfCV53ZsNN-MnVMoz41
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/gabrielvpina/Estat-stica/main/aula_estatistica%20-%20P%C3%A1gina2.tsv")
#importação do arquivo

# o comando "df.head" é usado para mostrar os itens listados na tabela (nesse caso 40 itens, de 0 a 39)
df.head(41)

df.describe()
#mostra algumas informações básicas da tablela, como quantidade de elementos, média, desvio padrão, valores mínimos e máximos

df.N.plot()
#gráfico que relaciona os valores dos elementos da coluna

df['N']
# mostra os elementos da coluna

